export const data = {
	animals: {
		easy: [
			"cat",
			"dog",
			"bat",
			"ant",
			"cow",
			"rat",
			"bee",
			"fox",
			"owl",
			"pig",
		],

		medium: [
			"tiger",
			"horse",
			"snake",
			"zebra",
			"panda",
			"sheep",
			"otter",
			"koala",
			"beaver",
			"donkey",
		],

		hard: [
			"elephant",
			"crocodile",
			"chimpanzee",
			"rhinoceros",
			"alligator",
			"kangaroo",
			"hippopotamus",
			"orangutan",
			"armadillo",
			"aardvark",
		],
	},
	movies: {
		easy: [
			"Up",
			"Jaws",
			"Rocky",
			"Frozen",
			"Titanic",
			"Gladiator",
			"Shrek",
			"Cars",
			"Aliens",
			"Speed",
		],
		medium: [
			"The Matrix",
			"Iron Man",
			"Star Wars",
			"The Godfather",
			"Inception",
			"Black Panther",
			"Toy Story",
			"The Lion King",
			"Jurassic Park",
			"Forrest Gump",
		],
		hard: [
			"The Silence of the Lambs",
			"Eternal Sunshine of the Spotless Mind",
			"No Country for Old Men",
			"Pirates of the Caribbean",
			"The Curious Case of Benjamin Button",
			"The Lord of the Rings",
			"Harry Potter and the Prisoner of Azkaban",
			"Indiana Jones and the Last Crusade",
			"Guardians of the Galaxy",
			"The Good the Bad and the Ugly",
		],
	},
	countries: {
		easy: [
			"Peru",
			"Italy",
			"Japan",
			"India",
			"Chile",
			"Kenya",
			"Nepal",
			"Spain",
			"Cuba",
			"Egypt",
		],
		medium: [
			"Germany",
			"Ireland",
			"Nigeria",
			"Austria",
			"Vietnam",
			"Belgium",
			"Morocco",
			"Hungary",
			"Sweden",
			"Finland",
		],
		hard: [
			"Argentina",
			"Philippines",
			"Switzerland",
			"Afghanistan",
			"Luxembourg",
			"Uzbekistan",
			"Kazakhstan",
			"Saudi Arabia",
			"Turkmenistan",
			"Papua New Guinea",
		],
	},
};
